AutoScan/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('scan/', include('scan.urls')),
    path('user/', include('user.urls')),
    path('subdomain/', include('subdomain.urls')),
    path('apptest/', include('apptest.urls')),
]

scan/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date     : 2021/4/21 14:41
# @Author   : zenggt

from django.urls import path
from . import views


urlpatterns = [
    path('index.html', views.index),
    path('detail.html', views.detail),
    path('addassert', views.addassert),
    path('assertstart', views.assertstart),
    path('webhook', views.xray_webhook),
    path('bugdetail.html', views.bugdetail),
]

user/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date     : 2021/4/22 9:54
# @Author   : zenggt

from django.urls import path
from . import views
urlpatterns = [
    path('register', views.register),
    path('sendsms', views.sendsms, name='sendsms'),
]

user/models.py
from django.db import models

# Create your models here.

class UserInfo(models.Model):
    mobile_phone = models.CharField(verbose_name='手机', max_length=32)
    username = models.CharField(verbose_name='用户名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=32)

user/views.py
from django.core.validators import RegexValidator
from django.core.validators import ValidationError
from django.shortcuts import render, HttpResponse
from django.http import JsonResponse
from user import models
from django import forms
from django.conf import settings
from plugins.tencent.sms import send_sms_single
import random
from django_redis import get_redis_connection



# Create your views here.


class RegisterModelForm(forms.ModelForm):
    # 定义手机号格式要求
    mobile_phone = forms.CharField(label='手机号', validators=[RegexValidator(r'^(1[3|4|5|6|7|8|9])\d{9}$', '手机号格式错误'),])
    # 定义密码不可见
    password = forms.CharField(label='密码', widget=forms.PasswordInput())
    confirm_password = forms.CharField(label='重复密码', widget=forms.PasswordInput())
    # 手机验证码
    mobile_code = forms.CharField(label='验证码')

    class Meta:
        model = models.UserInfo
        fields = "__all__"
    # 重写init,完成标签属性
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name,field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = '请输入%s' % (field.label)


def register(request):
    form = RegisterModelForm()
    return render(request, 'user/register.html', {'form': form})


class SendSmsForm(forms.Form):
    mobile_phone = forms.CharField(label='手机号', validators=[RegexValidator(r'^(1[3|4|5|6|7|8|9])\d{9}$', '手机号格式错误'),])

    # 自定义init:接收request
    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request

    # 手机号验证勾子
    def clean_mobile_phone(self):
        mobile_phone = self.cleaned_data['mobile_phone']

        # 短信模板验证
        tpl = self.request.GET.get('tpl')
        templates_id = settings.TENCENT_SMS_TEMPLATES[tpl]
        if not templates_id:
            raise ValidationError('短信模板错误')

        # 校验手机号是否存在
        exists = models.UserInfo.objects.filter(mobile_phone=mobile_phone).exists()
        if exists:
            raise ValidationError('手机号已存在')

        # 发短信
        code = random.randrange(1000,9999)
        sms = send_sms_single(mobile_phone, templates_id, [code, ])
        if sms['result'] != 0:
            raise ValidationError('短信发送失败, {}'.format(sms['errsmg']))

        # 将验证码写入redis(django-redis)
        conn = get_redis_connection() # 默认default
        conn.set(mobile_phone, code, ex=60) # 超时60s

        return mobile_phone

def sendsms(request):
    form = SendSmsForm(request, data=request.GET)
    # 是否为空、格式是否正确
    if form.is_valid():
        return JsonResponse({'status': True})
    return JsonResponse({'status': False, 'error': form.errors })

templates/user/login.html
<!DOCTYPE html>
<html>


<!-- Mirrored from www.zi-han.net/theme/hplus/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 20 Jan 2016 14:18:23 GMT -->
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <title>H+ 后台主题UI框架 - 登录</title>
    <meta name="keywords" content="H+后台主题,后台bootstrap框架,会员中心主题,后台HTML,响应式后台">
    <meta name="description" content="H+是一个完全响应式，基于Bootstrap3最新版本开发的扁平化主题，她采用了主流的左右两栏式布局，使用了Html5+CSS3等现代技术">

    <link rel="shortcut icon" href="/static/favicon.ico"> <link href="/static/css/bootstrap.min14ed.css?v=3.3.6" rel="stylesheet">
    <link href="/static/css/font-awesome.min93e3.css?v=4.4.0" rel="stylesheet">

    <link href="/static/css/animate.min.css" rel="stylesheet">
    <link href="/static/css/style.min862f.css?v=4.1.0" rel="stylesheet">
    <!--[if lt IE 9]>
    <meta http-equiv="refresh" content="0;ie.html" />
    <![endif]-->
    <script>if(window.top !== window.self){ window.top.location = window.location;}</script>
</head>

<body class="gray-bg">

    <div class="middle-box text-center loginscreen  animated fadeInDown">
        <div>
            <div>

                <h1 class="logo-name">H+</h1>

            </div>
            <h3>欢迎使用 H+</h3>

            <form class="m-t" role="form" action="http://www.zi-han.net/theme/hplus/index.html">
                <div class="form-group">
                    <input type="email" class="form-control" placeholder="用户名" required="">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="密码" required="">
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">登 录</button>


                <p class="text-muted text-center"> <a href="login.html#"><small>忘记密码了？</small></a> | <a href="register.html">注册一个新账号</a>
                </p>

            </form>
        </div>
    </div>
    <script src="/static/js/jquery.min.js?v=2.1.4"></script>
    <script src="/static/js/bootstrap.min.js?v=3.3.6"></script>
    <script type="text/javascript" src="http://tajs.qq.com/stats?sId=9051096" charset="UTF-8"></script>
</body>


<!-- Mirrored from www.zi-han.net/theme/hplus/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 20 Jan 2016 14:18:23 GMT -->
</html>

templates/user/register.html
<!DOCTYPE html>
<html>


<!-- Mirrored from www.zi-han.net/theme/hplus/register.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 20 Jan 2016 14:19:52 GMT -->
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <title>AutoScan 注册</title>
    <meta name="keywords" content="H+后台主题,后台bootstrap框架,会员中心主题,后台HTML,响应式后台">
    <meta name="description" content="H+是一个完全响应式，基于Bootstrap3最新版本开发的扁平化主题，她采用了主流的左右两栏式布局，使用了Html5+CSS3等现代技术">

    <link rel="shortcut icon" href="/static/favicon.ico">
    <link href="/static/css/bootstrap.min14ed.css?v=3.3.6" rel="stylesheet">
    <link href="/static/css/font-awesome.min93e3.css?v=4.4.0" rel="stylesheet">
    <link href="/static/css/plugins/iCheck/custom.css" rel="stylesheet">
    <link href="/static/css/animate.min.css" rel="stylesheet">
    <link href="/static/css/style.min862f.css?v=4.1.0" rel="stylesheet">
    <script>if (window.top !== window.self) {
        window.top.location = window.location;
    }</script>

    <style>
        .log {
            margin: auto;
            margin-left: -120px;
        }
        .error-msg {
            color: red;
        }
    </style>

</head>

<body class="gray-bg">

<div class="middle-box text-center loginscreen   animated fadeInDown">
    <div>
        <div>

            <h1 class="logo-name log">AutoScan</h1>

        </div>
        <h3>欢迎注册 AutoScan</h3>
        <p>创建一个AutoScan新账户</p>
        <form class="m-t" role="form" action="http://www.zi-han.net/theme/hplus/login.html">.
            {% for field in form %}
                {% if field.name == 'mobile_code' %}
                    <div class="form-group">
                        <div class="clearfix">
                            <div class="col-md-6">
                                {{ field }}
                                <span class="error-msg"></span>
                            </div>
                            <div class="col-md-6"><input id="btnSms" type="button" class="btn btn-default"
                                                         value="获取验证码"></div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        {{ field }}
                        <span class="error-msg"></span>
                    </div>
                {% endif %}
            {% endfor %}
            <div class="form-group text-left">
                <div class="checkbox i-checks">
                    <label class="no-padding">
                        <input type="checkbox"><i></i> 我同意注册协议</label>
                </div>
            </div>

            <button type="submit" class="btn btn-primary block full-width m-b">注 册</button>

            <p class="text-muted text-center"><small>已经有账户了？</small><a href="/user/login.html">点此登录</a>
            </p>

        </form>
    </div>
</div>


<script src="/static/js/jquery.min.js?v=2.1.4"></script>
<script src="/static/js/bootstrap.min.js?v=3.3.6"></script>
<script src="/static/js/plugins/iCheck/icheck.min.js"></script>
<script>
    $(document).ready(function () {
        $(".i-checks").iCheck({checkboxClass: "icheckbox_square-green", radioClass: "iradio_square-green",})
    });
</script>
<script type="text/javascript" src="http://tajs.qq.com/stats?sId=9051096" charset="UTF-8"></script>
<script>
    // 页面加载完成后自动执行的函数
    $(function () {
        bindClickBtnSms();
    });

    /*
    *  点击获取验证码事件
    * */
    function bindClickBtnSms() {
        $('#btnSms').click(function () {
            // 获取用户输入的手机号
            var mobilePhone = $('#id_mobile_phone').val();
            // 发送ajax请求
            $.ajax({
                url: "{% url 'sendsms' %}",
                type: "GET",
                data: {mobile_phone: mobilePhone, tpl: "register"},
                datatype: "JSON",
                success: function (res) {
                    if (res.status) {
                        console.log("success")
                    } else {
                        //打印错误信息 {status: false, error:{ }}
                        $.each(res.error, function (key, value) {
                            $("#id_" + key).next().text(value[0])
                        })
                    }
                }
            })
        })
    }
</script>


</body>
</html>